CREATE DATABASE OSCDB;

USE OSCDB;

CREATE TABLE IF NOT EXISTS person (
	id INT NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	FIRSTNAME VARCHAR(20),
	MIDDLENAME VARCHAR(20),
	GENDER CHAR(1) NOT NULL,
	BDAY DATE,
	GOVTID VARCHAR(20),
	PRIMARY_EMAIL VARCHAR(50),
	PRIMARY_PHONE VARCHAR(50)
);

